//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public int Salary { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
