//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ProjectWorks = new HashSet<ProjectWork>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Vacations = new HashSet<Vacation>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public System.Guid Type { get; set; }
        public bool IsRemoved { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<ProjectWork> ProjectWorks { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Vacation> Vacations { get; set; }
    }
}
