//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskState
    {
        public TaskState()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid Id { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
